name: vocal_coach_app
description: "AI Vocal Coach Flutter Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  file_picker: ^10.1.9
  path_provider: ^2.1.2
  permission_handler: ^12.0.0+1
  just_audio: ^0.9.36
  audio_waveforms: ^1.0.4
  flutter_ffmpeg: ^0.4.2
  youtube_explode_dart: ^2.0.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.7.7+1
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
